#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VM204.Resource", IsApplication=true)]

namespace VM204
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_new = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_navigation_next_item = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_navigation_refresh = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_search = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001a
			public const int EditButton = 2131165210;
			
			// aapt resource value: 0x7f07000b
			public const int OutputRelativeLayout = 2131165195;
			
			// aapt resource value: 0x7f07001c
			public const int RelayListView = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int RelayName = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int action_add = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int action_scan = 2131165216;
			
			// aapt resource value: 0x7f07000a
			public const int btnAdd = 2131165194;
			
			// aapt resource value: 0x7f07001b
			public const int btnSave = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int btnScan = 2131165213;
			
			// aapt resource value: 0x7f070015
			public const int checkBox1 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int checkBox2 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int checkBox3 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int checkBox4 = 2131165208;
			
			// aapt resource value: 0x7f070006
			public const int lblIp = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int lblName = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int lblPassword = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int lblPort = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int lblUserName = 2131165186;
			
			// aapt resource value: 0x7f070014
			public const int relativeLayout1 = 2131165204;
			
			// aapt resource value: 0x7f07001e
			public const int scanListview = 2131165214;
			
			// aapt resource value: 0x7f07000c
			public const int switch1 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int switch2 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int switch3 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int switch4 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int textView1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int textView2 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int textView3 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int textView4 = 2131165203;
			
			// aapt resource value: 0x7f070007
			public const int txtIp = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int txtName = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int txtPassword = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int txtPort = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int txtUserName = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ControlLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomRowView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ScanActivity = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int scanmenu = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int action_search = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int add = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int ip = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int name = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int password = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int port = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int save = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int username = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
